### ISSUE TITLE
Kraken reports including minimizer count information rise an exception

### ISSUE THREAD

**Issue by aeu79** [ewels/MultiQC#1379]
**Description of bug:**

Kraken2 reports that include minimizers information (KrakenUniq-like) generate and exception in MultiQC. These reports are generated using the `--report-minimizer-data` flag. 

**Workaround:**

As a workaround, the reports can be converted back to the standard format (8 to 6 columns) with:
```bash

for file in /path/to/your/reports/*.report; do
echo $file
cut -f1-3,6-8 $file > "${file}_standard.report"
done

```
**MultiQC run details (please complete the following):**

Sorry that I'm skipping the details and context, but I went through the code and I already have a fix. I'll polish a little the code and then I'll push to my fork so you can have a look.

**Comment by ewels** [comment]
Sounds good, I’ll wait for a PR then 👌🏻

If you’re able to attach some example data that would be great, then we can add that to ewels/MultiQC_TestData to ensure that it stays fixed in the future 👍🏻

**Comment by apeltzer** [comment]
Looks like #1380 really fixes it + visualizes the new output 👍🏻

**Comment by aeu79** [comment]
Ups, created the PR. Well, this was the first part only, so I'm glad I saw #1380 right now. Still, having a quick view to the code there, it doesn't solve the "original" problem. 
Although the regular expression seemed quite specific, the 8 columns report managed to go through security :guardsman: anyhow.
Have a look to this:
[Before](https://pythex.org/?regex=%5E%5Cs%7B1%2C2%7D(%5Cd%7B1%2C2%7D%5C.%5Cd%7B1%2C2%7D)%5Ct(%5Cd%2B)%5Ct(%5Cd%2B)%5Ct(%5B%5CdUDKPCOFGS-%5D%7B1%2C3%7D)%5Ct(%5Cd%2B)(%5Cs%2B)(.%2B)&test_string=6%20columns%3A%0A%20%200.00%094%094%09S3%091182172%09%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Salmonella%20enterica%20subsp.%20enterica%20serovar%20Bareilly%20str.%20CFSAN000661%0A8%20columns%3A%0A%20%200.00%094%094%0915%093%09S%09548914%09%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Elephant%20endotheliotropic%20herpesvirus%204%0A&ignorecase=0&multiline=1&dotall=0&verbose=0) and [After](https://pythex.org/?regex=%5E%5Cs%7B1%2C2%7D(%5Cd%7B1%2C2%7D%5C.%5Cd%7B1%2C2%7D)%5Ct(%5Cd%2B)%5Ct(%5Cd%2B)%5Ct(%5BUDKPCOFGS-%5D%5Cd%7B0%2C2%7D)%5Ct(%5Cd%2B)(%5Cs%2B)(.%2B)&test_string=6%20columns%3A%0A%20%200.00%094%094%09S3%091182172%09%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Salmonella%20enterica%20subsp.%20enterica%20serovar%20Bareilly%20str.%20CFSAN000661%0A8%20columns%3A%0A%20%200.00%094%094%0915%093%09S%09548914%09%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Elephant%20endotheliotropic%20herpesvirus%204%0A&ignorecase=0&multiline=1&dotall=0&verbose=0)

Now, if you accept my fix, it will certainly brake the one for #1380. So you will need another re for the 8 columns report (with minimizers).

**Comment by apeltzer** [comment]
@maxibor have a look at the above

**Comment by maxibor** [comment]
All your concerns should be addressed in #1380 @aeu79  @apeltzer 
Well @ewels , looks like there is a lot of demand for updating Kraken2: two PR on the same feature !

**Comment by ewels** [comment]
Should be fixed in #1380
