### ISSUE TITLE
GATK varianteval parsing error

### ISSUE THREAD

**Issue by raonyguimaraes** [ewels/MultiQC#619]
```
[ERROR  ]         multiqc : Oops! The 'gatk' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module gatk raised an exception: Traceback (most recent call last):
  File "/home/ec2-user/ms-analysis/venv/bin/multiqc", line 412, in multiqc
    output = mod()
  File "/home/ec2-user/ms-analysis/venv/lib64/python3.6/site-packages/multiqc/modules/gatk/gatk.py", line 41, in __init__
    n_reports_found += self.parse_gatk_varianteval()
  File "/home/ec2-user/ms-analysis/venv/lib64/python3.6/site-packages/multiqc/modules/gatk/varianteval.py", line 20, in parse_gatk_varianteval
    parsed_data = parse_single_report(f['f'])
  File "/home/ec2-user/ms-analysis/venv/lib64/python3.6/site-packages/multiqc/modules/gatk/varianteval.py", line 106, in parse_single_report
    d[headers[i]] = s
IndexError: list index out of range
============================================================
```

**Comment by ewels** [comment]
Thanks @raonyguimaraes - is it possible for you to send the file that triggers this error? It looks like it's due to a parsing error which usually means an unexpected input file format.

Phil

**Comment by raonyguimaraes** [comment]
Hi Phil,

Sorry if this sounds stupid but how do I know which file is causing the error? Shouldn't the name of the file appear in the logs? 

I'm running multiqc over 33513 files using the -v flag but it's not showing in the output which file is causing this error.

Here is the verbose output:

[2017-11-02 21:25:23,693] multiqc                                            [DEBUG  ]  No samples found: homer
[2017-11-02 21:25:23,696] multiqc                                            [DEBUG  ]  No samples found: macs2
[2017-11-02 21:25:23,700] multiqc                                            [DEBUG  ]  No samples found: theta2
[2017-11-02 21:25:23,703] multiqc                                            [DEBUG  ]  No samples found: snpeff
[2017-11-02 21:25:23,708] multiqc                                            [ERROR  ]  Oops! The 'gatk' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module gatk raised an exception: Traceback (most recent call last):
  File "/home/ec2-user/ms-analysis/venv/bin/multiqc", line 412, in multiqc
    output = mod()
  File "/home/ec2-user/ms-analysis/venv/lib64/python3.4/site-packages/multiqc/modules/gatk/gatk.py", line 41, in __init__
    n_reports_found += self.parse_gatk_varianteval()
  File "/home/ec2-user/ms-analysis/venv/lib64/python3.4/site-packages/multiqc/modules/gatk/varianteval.py", line 20, in parse_gatk_varianteval
    parsed_data = parse_single_report(f['f'])
  File "/home/ec2-user/ms-analysis/venv/lib64/python3.4/site-packages/multiqc/modules/gatk/varianteval.py", line 106, in parse_single_report
    d[headers[i]] = s
IndexError: list index out of range
============================================================
[2017-11-02 21:25:23,712] multiqc                                            [DEBUG  ]  No samples found: htseq
[2017-11-02 21:26:02,664] multiqc.modules.bcftools.bcftools                  [INFO   ]  Found 432 stats reports
[2017-11-02 21:26:02,671] multiqc                                            [DEBUG  ]  No samples found: featureCounts
[2017-11-02 21:26:02,684] multiqc                                            [DEBUG  ]  No samples found: picard
[2017-11-02 21:26:02,688] multiqc                                            [DEBUG  ]  No samples found: prokka

I can try to narrow it down but would be good if this error would show me which file has caused this.

**Comment by ewels** [comment]
This type of error is unexpected and not handled, so I'm afraid it's not possible to narrow it down any more. The only way to do this is to print a verbose log message when each log file parsing starts, and see what was reported last before it broke. MultiQC can't ship with this code as the log files would be enormous.

The exception trace says that the code is trying to parse more header columns than exist. This type of error is usually due to a variation in a tool's output, which is almost always version-specific. So my guess is that _all_ of your GATK varianteval files will cause this error. This module [looks for](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml#L149-L151) any files with the string `'#:GATKTable:TiTvVariantEvaluator'`, such as those [test data directory](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/gatk/varianteval). So if you can find one file like this and try running MultiQC on that alone, it should be pretty quick to check whether it causes the same error. If it doesn't, then you'll have to edit the MultiQC code in your installation to add a helper debug statement so that you can see which file it is which triggers the error. You can do this by adding a line in the `find_log_files` loop [here](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/gatk/varianteval.py#L19):

```python
log.debug("Parsing file '{}'".format(f['fn']))
```

Once we know what your file format looks like, we can add code to handle the error nicely. But by the time we know that, hopefully we should be able to fix the error instead.

Finally - could you paste the top of the log where MultiQC reports the exact version that you're running please? This module is only available in v1.3dev and is pretty new, so it's good to check that you're running the latest version of MultiQC (though this module hasn't been updated in a little while, so I doubt it's that).

Pinging @winni2k as he wrote this module.

Phil

**Comment by winni2k** [comment]
@ewels thanks for the ping. Actually, this is in part of the GATK report parsing that was there before I got involved. However, I'm happy to provide some maintenance for it. @raonyguimaraes, if you could post a [minimal example](https://stackoverflow.com/help/mcve) of a GATK report that crashes the parser, then that would go a very long way to fixing this problem quickly.

**Comment by winni2k** [comment]
It looks I'm pretty sure the error is raised inside `parse_single_report` somewhere: https://github.com/ewels/MultiQC/blame/master/multiqc/modules/gatk/varianteval.py#L81

When we fix the bug, we should probably also refactor this function.

**Comment by ewels** [comment]
Hi @raonyguimaraes,

I had a think about your request of reporting the file that triggers the error in the logs. I think I figured out a way to do it after all, I've just pushed the change. If you run the latest version of MultiQC again, the error message should now tell you what the last file that MultiQC found was.

I hope this helps!

Phil

**Comment by raonyguimaraes** [comment]
Hi Phil,

I think we are almost there! I still can't see the name of the file in the output. It looks empty, I tried printing the f dict and it says it's None.

**Comment by winni2k** [comment]
@ewels It looks like the "last file found" feature is returning a multiqc module file (`varianteval.py`) instead of a GATK report?

**Comment by ewels** [comment]
That _should_ be impossible.. (see code [here](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/base_module.py#L100)). @raonyguimaraes is that log copied and pasted straight from MultiQC? Could you send the `multiqc_data/multiqc.log` file from that run please?

Phil

**Comment by ewels** [comment]
Closing due to inactivity. If this is still a problem we can reopen.
